from distutils.core import setup
setup(
  name = 'fontcheck',
  packages = ['fontcheck'],
  version = '0.1',
  license='MIT',
  description = 'A very simple program to check if a text contains special 𝒻𝑜𝓃𝓉𝓈.',
  author = 'nsde',
  author_email = 'neostyxde@gmail.com',
  url = 'https://github.com/nsde',
  download_url = 'https://github.com/nsde/fontcheck/archive/v0.2.tar.gz',
  keywords = ['FONT', 'FONTCHECK', 'CHECK'],
  install_requires=[],
  classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
  ],
)
